language: node_js
node_js:
  - '6'
  - '7'
  - '8'
cache: yarn
script:
  - npm run prepush
    # get the coverage metrics to coveralls
  - cat coverage/typescript/lcov.info | ./node_modules/coveralls/bin/coveralls.js
